### ISSUE TITLE
when including external JS, bundler includes html instead

### ISSUE THREAD

**Issue by caseyyee** [aframevr-userland/aframe-cli#19]
As part of https://github.com/aframevr-userland/aframe-cli/pull/17, I tried including the component script into it's own `js/components/teleport.js`.

The bundler ends up concatenating the html itself.  Not sure why.

**Comment by cvan** [comment]
@caseyyee can you show me a screenshot and/or a `git diff`?

see how I used a custom component in `templates/aframe-360-image-gallery-template/`:

* https://github.com/aframevr-userland/aframe-cli/blob/c1fb61e/templates/aframe-360-image-gallery-template/app/js/initialize.js#L13-L14
* https://github.com/aframevr-userland/aframe-cli/blob/master/templates/aframe-360-image-gallery-template/app/js/components/set-image.js

btw, it was probably confusing with the `app.js` and `initialize.js` in the Default template (there's no `app.js` in the 360° Image Gallery template. I've since removed from the Default template (4ad4259) and from the Room template too (cf4e304).

**Comment by caseyyee** [comment]
@cvan
https://github.com/aframevr-userland/aframe-cli/compare/master...caseyyee:packager?expand=1

![image](https://cloud.githubusercontent.com/assets/1560884/26693156/082b0c60-46b8-11e7-93da-429d27342003.png)

![image](https://cloud.githubusercontent.com/assets/1560884/26693196/2d0c6fec-46b8-11e7-9c67-b9815e15668c.png)

**Comment by cvan** [comment]
so, that's because all the JS files get combined into one: `app.js`. that's the default behaviour. that's a little confusing, so maybe I should stop that.

you should never ever need to modify the HTML to add a `<script>` (like [in here](https://github.com/aframevr-userland/aframe-cli/blob/c1fb61ec/templates/aframe-360-image-gallery-template/app/assets/index.html#L8-L9)).

JS packages, as scripts in the `js` directory as packages from `npm`, they should always be [required](https://github.com/aframevr-userland/aframe-cli/blob/c1fb61e/templates/aframe-360-image-gallery-template/app/js/initialize.js#L13-L14) (since we're using Browserify after all).

there could be better error messages or warnings; I totally agree.

this is definitely not perfect, so this is good: keep the feedback coming so we can figure out what will be comfortable for other/most folks.

**Comment by caseyyee** [comment]
Oh that makes sense.   I totally didn't realize browserify was being used.  I guess I should have noticed in `app.js`.   My bad.  Will revise.

**Comment by cvan** [comment]
yeah, maybe things are too magical. plan on documenting that. that's that what happens in `aframe serve` - it's magical. docs for the underlying build system, Brunch, can be found here: http://brunch.io/docs/getting-started

filed issue #24 to track adding docs. sorry for making it not totally obvious
